### ISSUE TITLE
Plans for releasing?

### ISSUE THREAD

**Issue by rouson** [sandialabs/seacas#118] opened 2018-09-18 17:21 UTC
Are there any plans to produce a release of this repository?   The primary motivations for this request relate to the implicit stability that releases communicate and the workflow they enable through knowing that

* I can always download the same snapshot of the archive using `curl` or `wget`
  -  Otherwise, I'm required to use `git checkout <commit-hash>` to get the snapshot I want.
* I can accomplish that download of a specific snapshot without a browser.

As a corollary, users would know that published releases will be static and immutable.

Thoughts?

**Comment by gsjaardema** [comment] 2018-09-18 17:38
Throughout its history, we have always followed a "continuous intgration" type of philosophy -- every snapshot from the repository should be usable.  Looking back through the commit history, that obviously doesn't always hold as there have been times when I have committed code that temporarily broke the build...  

 I will a look at periodically tagging releases when it would sense.  However, for now the best I can offer is just using a specific commit

**Comment by zbeekman** [comment] 2018-09-18 18:00
Part of the motivation for this was due to the usage of the exodus.zip file, which confusingly, downloads a seacas-exodus.zip file and how/when/why that URL gets updated is completely opaque. Presumably we can just use the main repository to build the exodus library, which we're looking into. At least tagging in git would be helpful to indicate more stable commits...

Also, releases and tagging can help communicate breaking changes, new capabilities, etc. if you use semantic versioning.

Any way, thanks for the fast response. I would love to see at least tags in git, if not full release archives.

Thanks!

**Comment by gdsjaar** [comment] 2018-10-18 20:36
I have been planning to add some tags for “stable release” periodically.  As for Version numbers, each individual application and most libraries have a version number; I don’t think there is any good way to have a “SEACAS” version that is anyway meaningful.

..Greg

**Comment by gsjaardema** [comment] 2018-10-19 12:28
Exodus does and always has had a version number.  

All individual applications and the exodusII library have always had version numbers.  It is the overall SEACAS agglomeration that does not have a version number or a tagged repository.

**Comment by mathstuf** [comment] 2018-10-19 12:49
Ah, I guess what's missing then are tags for the subprojects.

**Comment by mathstuf** [comment] 2018-10-21 14:16
@zbeekman It's just hanging out in [a header file](https://github.com/gsjaardema/seacas/blob/master/packages/seacas/libraries/exodus/include/exodusII.h#L72).

**Comment by zbeekman** [comment] 2018-10-21 15:50
@mathstuf thanks for pointing me to that. Not the most transparent/user friendly release management system here 🤔 ... but I'll take what I can get.

**Comment by gsjaardema** [comment] 2018-10-21 22:50
@zbeekman ?  How was that at l helpful?

**Comment by rouson** [comment] 2018-10-22 04:55
@gsjaardema I'm really struggling with understanding the downside of producing a tagged releases.  It could literally be accomplished in seconds of your time and would therefore seem to be much less costly than furthering this debate when four users have now added their voices, including me, @zbeekman (who collaborates with me), @bmpersc, and @mathstuf.  We get that you don't see great value and that you see some ambiguity in that various included packages or dependancies will each haver their own versioning system that might not be easily reconcilable, but at the end of the day, the version number isn't much more than a time stamp and a rough indication of stability. Unless  you think the implication of stability is harmful (in which case there are bigger problems to address), it's hard to understand the resistance.

**Comment by zbeekman** [comment] 2018-10-22 13:50
@Rouson If I'm looking at the source correctly, it looks like there are a number of sub-projects that are contained in the main seacas repository. So one complexity is that seacas will get versioned... fine, but the dependencies, also kept in this repository, have their own versions. So a single tag for the repository doesn't really seem to be adequate because vendored sub-projects e.g., exodus, may be at a different version than seacas itself.

This Seacas strikes me as a project that could benefit from git submodules, if the developers are proficient enough with git, and comfortable with the idea. Then each of the sub projects could have it's own repository, and get pulled in to seacas as a submodule. This way, the exodus distribution could be tagged, and released in the exodus repository and then seacas can be tagged and released independently and consume exodus as a dependency.

Just my $0.02, but I think this is how I would maintain this project and manage releases if I were in charge of it. This would make it easier for users who are looking for a single component (e.g., exodus) to obtain that component, and have a more transparent system for determining the version and the provenance of the release assets.

Anyway, sorry to be a trouble maker, @gsjaardema, and thanks for your work in maintaining all of this.

**Comment by gsjaardema** [comment] 2018-10-22 14:31
@rouson I don't think I am furthering any debate or resistant to tagging the repository.  Four days ago I said:

> I have been planning to add some tags for “stable release” periodically.  As for Version numbers, each individual application and most libraries have a version number; I don’t think there is any good way to have a “SEACAS” version that is anyway meaningful.

I'm not sure why you would think that the implication of stability is harmful or why there is resistance. 

I guess I should have taken time away from my family and addressed this over the weekend?  Sorry for having a life.

Just to make it clear, I repeat that I will look into tagging the repository with meaningful tags in the near future.

**Comment by rouson** [comment] 2018-10-23 03:35
@gsjaardema One of the things I loved about my 5.5 years at Sandia was the extent to which work/life balance was respected and supported.  Family time always comes first.  I'm glad you plan to tag the repository.  If the git submodule approach proposed by @zbeekman is of interest, I hope I can speak for both of us in saying we would be glad to assist with the process of setting it up. The proposed approach would ultimately benefit a project we have that depends on Exodus II.

**Comment by gsjaardema** [comment] 2018-10-23 15:50
@rouson We discussed using git submodules when originally setting up the SEACAS github repository.  At the time, I think that the submodule support was not totally robust and also the SEACAS repository is replicated into other repositories (Trilinos, an internal CFD code, and an internal FE code framework).  Some of these use submodules and some don't.

I haven't looked at the possible issues of using submodules in a repository that is itself a submodule in another repository so not familiar with potential issues.   I also need a good way to "snapshot" the SEACAS repository into another repository.  The current tool that I use is in `cmake/tribits/snapshot_tribits.py'

I guess the bottom line is that I am fine with investigating the use of submodules, but there are some  external users of SEACAS that we need to make sure are not affected by this change.

**Comment by mathstuf** [comment] 2018-10-24 13:04
Making an archive of a repository with submodules is best done with [`git-archive-all`](https://github.com/Kentzo/git-archive-all) since `git archive` just gives empty subdirectories.

**Comment by sknigh** [comment] 2019-07-22 18:34
@gsjaardema Has there been any progress on this? Releases (or least git tagging) is essential for build reproducibility. Tagging the API version (EX_API_VERS_NODOT) when it changes would be fine, even just tagging the repository with a date (ISO 8601) every couple of months would be enough to satisfy this need.

**Comment by gsjaardema** [comment] 2019-07-24 21:02
@sknigh Sorry, I keep meaning to do this and everytime I am ready to tag it seems like I start making changes and then wait.

I periodically sync the code over to Trilinos which would be a good time to tag, so I will try to start doing that with the next sync (in a few days)

**Comment by gsjaardema** [comment] 2019-07-24 21:45
I tagged the current version of seacas with `v2019-07-24` which is the same version which is currently being synced to Trilinos. I will hopefully continue with tagging approximately monthly or whenever the changes are such that I sync with Trilinos or an internal repository at Sandia.

**Comment by sknigh** [comment] 2019-07-24 21:49
Thanks!

**Closed as completed** 2019-09-12 16:53 UTC
Labels: enhancement
